version: '3'
services:
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: my-nginx-image
    ports: 
      - "443:443"
    volumes:
      - "/home/aaggoujj/data:/etc/nginx/http.d"
    
