version: '3.3'
services:
  #########       Nginx         #############
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:1337
    restart: on-failure
    depends_on:
      - wordpress
    ports: 
      - "443:443"
    volumes:
      - type: volume
        source: wp-volume
        target: /var/www/html
    networks:
      - net
  
    #########       Mariadb         #############

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:1337
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    networks:
      - net
    volumes:
      - type: volume
        source: mariadb-volume
        target: /var/lib/mysql

  #########       Wordpress         #############

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:1337
    container_name: wordpress
    depends_on:
      - mariadb
    restart: on-failure
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - type: volume
        source: wp-volume
        target: /var/www/html
    networks:
      - net


volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aaggoujj/data/mariadb
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aaggoujj/data/wordpress

networks:
  net:
    
