version: '3'
services:
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:1337
    ports: 
      - "443:443"
    volumes:
      - type: volume
        source: nginx-volume
        target: /etc/nginx/http.d
  
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:1337
    container_name: database
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: abcd123
      MYSQL_DATABASE: mariadatabbase
      MYSQL_USER: mariadbuser
      MYSQL_PASSWORD: abcd123
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mariadb-volume
        target: /var/lib/mysql
  # wordpress:
  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: Dockerfile
  #   image: wordpress:1337
  #   container_name: wordpress


volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aaggoujj/data/mariadb
  nginx-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aaggoujj/data/nginx
    
