version: '3.3'
services:
  #########       Nginx         #############
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:1337
    restart: on-failure
    depends_on:
      - wordpress
    ports: 
      - "443:443"
    volumes:
      - type: volume
        source: wp-volume
        target: /var/www/html
    networks:
      - net
  
    #########       Mariadb         #############

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:1337
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    networks:
      - net
    volumes:
      - type: volume
        source: mariadb-volume
        target: /var/lib/mysql

  #########       Wordpress         #############

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:1337
    container_name: wordpress
    depends_on:
      - mariadb
    restart: on-failure
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - type: volume
        source: wp-volume
        target: /var/www/html
    networks:
      - net
      - net-redis-wordpress
  
  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: wp-volume
        target: /var/www/html
    depends_on:
      - wordpress
    ports:
      - "800:800"
    networks:
      - net

  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image:  redis:1337
    container_name: redis
    ports: 
      - "6379:6379"
    restart: on-failure
    networks:
      - net-redis-wordpress
  # chess:
  #   build:
  #     context: ./requirements/bonus/myservice/chess
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "4003:5000"
  myservice:
    build:
      context: ./requirements/bonus/myservice/portainer
      dockerfile: Dockerfile
    image: myservice:1337
    container_name: portainer
    ports:
      - "9443:9443"
      - "8000:8000"
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aaggoujj/data/mariadb
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aaggoujj/data/wordpress
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aaggoujj/data/portainer
    

networks:
  net:
  net-redis-wordpress:
    
